### ISSUE TITLE
Некорректная обработка параметров коммандной строки под Arch Linux

### ISSUE THREAD

**Issue by efeklisov** [Ray-Tracing-Systems/kernel_slicer#4]
# Операционая Система:
Arch Linux 5.13.9-zen
# Версии Clang и LLVM:
12.0.1
# Описание проблемы:
При сборке примеров программ через kernel_slicer (GLSL пресет) некорректно считываются флаги компиляции:

`-DKERNEL_SLICER` - его не видит библиотека LightMath и пытается собирать программу с SSE инструкциями. https://pastebin.com/wvupszSm

`-stdlibfolder TINYSTL` - после ручной замены заголовочного файла `OpenCLMathVEX.h` на `OpenCLMathCPU.h` в предыдущем примере kernel_slicer пытается найти `stddef.h` не в TINYSTL, а в стандартной библиотеке GCC 11 https://pastebin.com/HzjgAvkw

Для запуска использовались профили из launch.json. а также команда ```./kslicer apps/01_intersectSphere/test_class.cpp -stdlibfolder TINYSTL -pattern rtv -Iapps/LiteMath IncludeToShaders -shaderCC glsl -DKERNEL_SLICER -v```

# Шаги для сборки kernel_slicer на Arch Linux
- Заменить содержимое CMakeLists.txt следующим https://pastebin.com/HJc3aEqu
- Заменить в файлах `kslicer_main.cpp` и `extractor.cpp` enum `clang::ast_type_traits::TK_IgnoreUnlessSpelledInSource` на `clang::TK_IgnoreUnlessSpelledInSource`

Собранная версия kernel_slicer: https://drive.google.com/file/d/1dl7d6tXCTUyEqliIrr5zRefqw3BIgXqn/view?usp=sharing

**Comment by FROL256** [comment]
1) Заменил мат. библиотеку, убрал векторные инструкции от греха подальше.
2) Перешёл на LLVM12.
(эти 2 изменения запушал в мастер, так что теперь немного проще)
------------------------------------------------------------------------------------- 

3) установил Arch по инструкции https://phoenixnap.com/kb/arch-linux-install на qemu
4) модицифировал CMake 
5) CMake сгенерировался нормально
6) Поставил через пакман просто "llvm" и "clang", без этого не находились хидеры.
7) Собралось
8) Пока что не работает, скрины: 

https://disk.yandex.ru/i/FFNJcUMMxBTqzQ
https://disk.yandex.ru/i/_WAbCsPFY8935A (видно что командная строка передалась нормально)
https://disk.yandex.ru/i/9SqiClq5OUkQqA (видно что командная строка передалась нормально)

-------------------------------------------------------------------------------------

Суть проблемы приблизительно ясна, но детали пока нет. 
Очевидно что разница в инсталяциях clang для убунты и в Arch:

1) Если под убунтой по инструкции ставятся библиотеки llvm-12-dev и libclang-12-dev, то под Arch мы поставили просто llvm и clang (верно? или ты ставил что-то другое?)
   По-моему это не совсем то же самое. Но допустим. Мы взяли их хидеры и слинковали "-lclang -lLLVM -lclang-cpp", а что это такое?
   Видимо это библиотеки в папке рабочего clang-а, который прямо в системе стоит и используется для сборки.

2) Исходно я добавлял папку TINYSTL как раз по той причине что при использовании библиотек llvm-12-dev и libclang-12-dev clang вообще не находил stl и стандартные библиотеки.
   Поэтому я ему подсовывал "свой STL" в котором зачастую даже не реализованы функции, достаточно было их только определить.
   Ну реализовывать функции не нужно т.к. работа с кодом ведётся только на уровне AST дерева.

3) Сейчас происходит следующее:
   Из LiteMath.h мы лезем в "cmath" и попадаем куда-то в /usr/lib64/gcc/x86_64-pc-linux-gnu/.../cmath
   Из него мы лезем в                                    /usr/lib64/gcc/x86_64-pc-linux-gnu/.../std_abs.h
   Из него мы лезем в "stddef.h" которого почему-то не находим
   
   Итак, здесь меня смущает 2 вещи:
   3.1) Если мы используем clang то почему полезли в папку gcc
   3.2) Даже если мы туда полезли почему там нет stddef.h

В принципе несовместимость стандартных библиотек между gcc и clang как раз возможна.
На ранних этапах я пробовал подсовывать clang-у библиотеки из gcc и встречал самые разные проблемы.
В итоге я решил что проще держать свой маленький stl, тем более что его не нужно реализовывать а достаточно только определить.
Ну и в этом всё-таки есть некоторы преимущества. Например мы можем убрать те функции которые не поддерживаем при желании.

-------------------------------------------------------------------------------------   
Что нам надо сделать: 

1) Надо разобраться в том что именно ставиться в убунте и в Arch и написать инструкцию по инсталяции в Arch.
На худой конец можно собирать kslicer как тулзу составе llvm (я могу написать инструкцию). 
Я так делал поначалу, но это очень неудобно. Но зато оно собирается не с абы-какими библиотеками, а именно с той версией llvm, которая выкачена в текущую папку.
И там уже таких проблем быть не должно.

2) В идеале всё-таки неплохо было бы научиться подсовывать слайсеру настоящий stl потому что определять каждый раз отсутствующие функции это довольно муторно.
   Но я пока не знаю как это сделать, ведь на разных системах он может стоять в разных местах. 

У меня мало опыта с Arch (вот 1 раз поставил) )  
Если не трудно попробуй пж. разобраться как в Arch ставят clang библиотеки для разработки различных тулзов, работающих с AST деревом. Таких довольно много, например всякие переименовывания и статический анализ кода. 

Еслит не получится, попробуем сборку в составе llvm.

**Comment by FROL256** [comment]
При сборке в составе llvm проблема воспроизводится.

**Comment by FROL256** [comment]
https://clang.llvm.org/docs/FAQ.html
https://clang.llvm.org/docs/LibTooling.html#libtooling-builtin-includes (Builtin includes)

Thus, the default location to look for builtin headers is in a path $(dirname /path/to/tool)/../lib/clang/3.3/include relative to the tool binary.

В целом понятно что делать, но с новой стандартной библиотекой там возникают нюансы, я поправлю.

**Comment by FROL256** [comment]
Поправил пару багов и сделал документацию по сборке в составе LLVM. 
Но теперь должно работать и обычным способом!

clang ищет свои библиотеки в папке "../lib/clang/12.0.0/include" относительно той папки из которой он запускается
Нужно создать такую папку и скопировать туда содержимое "llvm12/build/lib/clang/12.0.0/include"

Я его вот сюда положил чтобы не собирать llvm: https://disk.yandex.ru/d/wboOCmqMhhaBMw

**Comment by efeklisov** [comment]
Да, после выполнения
```
cd kernel_slicer
mkdir ../lib && cp -r /usr/lib/clang/ ../lib
```
заработало
